/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.erickweil.estruturas;

public class PilhaArray {

    public static void main(String[] args) {
        System.out.println("Vamos Implementar Pilhas");
    }
}
