/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.erickweil.estruturas;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import org.junit.jupiter.api.Test;

import br.erickweil.Inicio;

class InicioTest {
    @Test void inicioFunciona() {
        Inicio classUnderTest = new Inicio();
        assertNotNull(Inicio.class, "classe Existe");
    }
}
